# Generated by Django 4.2.6 on 2023-12-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
