# Generated by Django 4.2.6 on 2023-12-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
