# Generated by Django 4.2.6 on 2023-12-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_point_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='username',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
